#!/bin/bash
FILE=/etc/apparmor.d/local/usr.sbin.mysqld
IFILE=/etc/init.d/apparmor
FTMP=`mktemp /tmp/tmp.XXXXXX`
if [ -f $FILE ]
then
  grep -v "@{HOME}/.config/cqrlog/database/" $FILE >> $FTMP
  cat $FTMP > $FILE
  echo ""
  echo Changes removed from $FILE
  echo "Restarting apparmor..."
  echo ""  
  if [ -f $IFILE ]
  then
    if which invoke-rc.d >/dev/null 2>&1; then
       invoke-rc.d apparmor restart
    else
      /etc/init.d/apparmor restart
    fi
  fi
fi

MFILE=/etc/apparmor.d/local/mariadbd
if [ -f $MFILE ] && grep -q "@{HOME}/.config/cqrlog/database/" $MFILE
then
  grep -v "@{HOME}/.config/cqrlog/database/" $MFILE > $FTMP
  cat $FTMP > $MFILE
  echo Changes removed from $MFILE
  if [ -f /etc/apparmor.d/mariadbd ] && which apparmor_parser >/dev/null 2>&1; then
    apparmor_parser -r /etc/apparmor.d/mariadbd || true
  fi
fi
rm $FTMP
#DEBHELPER#
