.\" Process this file with
.\" groff -man -Tascii cqrlog.1
.\"
.TH CQRLOG 1 "MAY 2011" Linux "User Manuals"
.SH NAME 
CQRLOG \- Advanced logging program for hamradio operators
.SH DESCRIPTION
.B CQRLOG
is an advanced ham radio logger based on MySQL database. Provides radio control based on hamlib libraries 
(currently support of 140+ radio types and models), DX cluster connection, QRZ callbook (web version), a grayliner, 
internal QSL manager database support and a most accurate country resolution algorithm based on country tables 
developed by OK1RR. CQRLOG is intended for daily general logging of HF, CW & SSB contacts and strongly focused on easy 
operation and maintenance.
.SH BUGS
Please report bug to email <petr at ok7an.com> or to CQRLOG home page http://www.cqrlog.com
.SH AUTHOR
Petr Hlozek, OK7AN <petr at ok7an.com>
