#!/bin/bash
 
VERSION=2.0.1
# cqrlog version

FINAL=/home/ok2cqr/projects/final_cqrlog/
#whre would you like to store final build files

#****************************************
CTMP=`mktemp -d /tmp/tmp.XXXXXX`
platform=`uname -m`
REL=/tmp/cqrlog-$VERSION
case $platform in
"x86_64")
	ARCH=`echo "amd64"`
	;;
*)
	ARCH=`echo "i386"`
	;;
esac
echo cqrlog_"$VERSION"_$ARCH.tar.gz

mkdir $CTMP/cqrlog-$VERSION -p
mkdir $FINAL -p
cd $CTMP
#svn co https://cqrlog.svn.sourceforge.net/svnroot/cqrlog/trunk cqrlog-$VERSION
git clone git://github.com/ok2cqr/cqrlog.git cqrlog-$VERSION
tar -cvf cqrlog_$VERSION.orig.tar --exclude='debian' --exclude='.git' cqrlog-$VERSION
gzip -v9 cqrlog_$VERSION.orig.tar
cd cqrlog-$VERSION
debuild -i -I -S
dpkg-buildpackage -rfakeroot -i -I
make clean
cd ..
tar -cvf cqrlog_$VERSION.deb.src.tar cqrlog*.orig.tar.gz cqrlog*.debian.tar.gz cqrlog*.debian.tar.xz cqrlog*.changes cqrlog*.dsc
gzip -v9 cqrlog_$VERSION.deb.src.tar

pwd
echo $FINAL
ls -lh cqrlog*.deb
ls -lh cqrlog*.deb.src.tar.gz
cp cqrlog*.deb $FINAL
cp cqrlog*.deb.src.tar.gz $FINAL

cd cqrlog-$VERSION
make
make DESTDIR=$REL install
cd /tmp
tar -cvf cqrlog_"$VERSION"_$ARCH.tar cqrlog-$VERSION
gzip -v9 cqrlog_"$VERSION"_$ARCH.tar
cp cqrlog_"$VERSION"_$ARCH.tar.gz $FINAL

